# Generated by Django 3.0.4 on 2020-04-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_auto_20200420_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
